### PR TITLE
(WIP V2) Pulse v2 Docs

### PR DESCRIPTION
**Pull request by Snipey**
## Description

Updated docs to have custom theme components and an open source changelog
Features
- TailwindCSS
- Custom Vue Modules
- Readme based Changelog

UPDATE:
- [x] Docs need to be combed for dead links and style needs tweaked. 
- [x] Re-Arrange some modules.
- [ ] Fix custom containers
- [ ] Add floating sidebar in guide
- [ ] Change guide font
- [x] Fix the markdown containers
- [x] Add dedicated contributors page.
- [x] Fix code quality.
- [ ] Fix the styles of the docs
- [ ] Highlight the page you are on in the guide in the sidebar and nav

PROPOSED:
- A full reference API to display what you should expect from the function
- Add a dropdown for package version specific docs

## Context
Version 2 of docs

### CODE REVIEW

**Comment by twigeee** [comment]
The location of the tailwind CSS config in `docs/.vuepress/config.js` needs to be changed from
`require('tailwindcss')('./tailwind.config.js'),` to 
`require('tailwindcss')('./docs/tailwind.config.js'),`
as right now, it's looking for the file in the root folder, when it's actually in the docs/ folder.

**Comment by f3ltron** [comment]
what u mean by  Add floating sidebar in guide ?

**Comment by Snipey** [comment]
Something like https://www.w3schools.com/howto/howto_css_fixed_sidebar.asp

**Comment by f3ltron** [comment]
the sidebar from vuepress is not enough ?

I am from the core team vuepress now 👍 tell me if you need infos to your doc

**Comment by Snipey** [comment]
No it was enough I just wanted to push vuepress to its limits using all the knowledge gathered from everyone who has made their own modifications and plugins.

**Comment by Snipey** [comment]
on hold atm

**Comment by Snipey** [comment]
Waste of time

**Pull request closed without merging**
